supabase.url=https://rxwijdozdixhihsktcjh.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4d2lqZG96ZGl4aGloc2t0Y2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3OTE0MzcsImV4cCI6MjA4OTM2NzQzN30.NsHQ7Pd-tjnd-zFGhqrzjH4w0aIMNk4GImb4l5mhH6M
supabase.storage-bucket=service-images
supabase.service-role=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4d2lqZG96ZGl4aGloc2t0Y2poIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mzc5MTQzNywiZXhwIjoyMDg5MzY3NDM3fQ.iRQP0JXKn93VYZbWRC2SUXywHOAFG30rcYaGha3C1uo

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.rxwijdozdixhihsktcjh
spring.datasource.password=AReNioSpxdb50pi3
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8085

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

#spring.jpa.properties.hibernate.format_sql=true

# HikariCP Configuration
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=10000

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Reduce connection usage
spring.jpa.open-in-view=false

# Logging configuration
logging.level.br.com.senai.controller=DEBUG
logging.level.br.com.senai.service=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO

# Para ver todos os logs da aplicação
logging.level.br.com.senai=DEBUG

# Formato dos logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n