# Dev profile logging
logging.level.br.com.senai=DEBUG
logging.level.br.com.senai.controller=DEBUG
logging.level.br.com.senai.service=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO

# Dev JPA
spring.jpa.show-sql=true
