# Prod profile logging
logging.level.br.com.senai=INFO
logging.level.br.com.senai.controller=INFO
logging.level.br.com.senai.service=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN

# Prod JPA
spring.jpa.show-sql=false
